import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {fromImageToUrl, API_URL} from "../utils/urls";

export default function Home({vegetables}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {vegetables.map(veg => (
            <div key={veg.title} className={styles.veg}>
                <div className={styles.product__Row}>
                    <div className={styles.product__ColImg}>
                        <img src={fromImageToUrl(veg.image)} />
                    </div>
                    <div className={styles.product__Col}>
                        {veg.title} {veg.unit_name}
                    </div>
                </div>

            </div>
        ))}
    </div>
  )
}

export async function getStaticProps(){
    const vegetables_res = await fetch(`${API_URL}/vegetables`)
    const vegetables = await vegetables_res.json()

    return{
        props: {
            vegetables : vegetables
        }
    }
}